export const LOGIN_USER_ACTION = "LOGIN_USER_ACTION";
export const LOGOUT_USER_ACTION = "LOGOUT_USER_ACTION";
export const VERIFY_USER_ACTION = "VERIFY_USER_ACTION";
export const REGISTER_NEW_USER_ACTION = "REGISTER_NEW_USER_ACTION";
export const EDIT_PROFILE_DATA_ACTION = "EDIT_PROFILE_DATA_ACTION";

export const ADD_BOOK_TO_FAVORITES_ACTION = "ADD_BOOK_TO_FAVORITES_ACTION";
export const REMOVE_BOOK_FROM_FAVORITES_ACTION = "REMOVE_BOOK_FROM_FAVORITES_ACTION";

export const ADD_FRIEND_ACTION = "ADD_FRIEND_ACTION";
export const REMOVE_FRIEND_ACTION = "REMOVE_FRIEND_ACTION";